***Support Vector Machines***
    Using SVM with Python to predict whether a breast cancer tumor is malignant or benign. Exercise uses numpy, pandas, and scikitlearn and utilizes train test split, SVM, SVC,  and GridSearch to identify the best parameters for prediction.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
cancer = load_breast_cancer()

In [4]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
print(cancer['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [6]:
cancer['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [32]:
df_feat = pd.DataFrame(cancer['data'],columns=cancer['feature_names'])
df_feat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [33]:
df_target = pd.DataFrame(cancer['target'],columns=['Cancer'])

In [43]:
X = df_feat
y = df_target['Cancer']

from sklearn import preprocessing
from sklearn.model_selection import train_test_split

cols = X.columns
df = pd.DataFrame(X)
df

min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(df)
df_normalized = pd.DataFrame(np_scaled, columns = cols)

X = df_normalized

y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: Cancer, Length: 569, dtype: int32

In [44]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
X_test

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
421     0.364854      0.144403        0.376132   0.217434         0.455629   
47      0.292915      0.302672        0.291549   0.165896         0.570281   
292     0.282503      0.213392        0.271923   0.157031         0.432157   
186     0.536182      0.299966        0.516965   0.380700         0.300172   
414     0.385678      0.679743        0.365697   0.244327         0.275977   
..           ...           ...             ...        ...              ...   
318     0.097544      0.310788        0.112501   0.042842         0.424754   
375     0.434900      0.215083        0.431967   0.273595         0.416810   
18      0.607175      0.420697        0.595743   0.473595         0.412386   
168     0.496427      0.506256        0.499689   0.356776         0.471879   
361     0.299068      0.401082        0.286435   0.170774         0.299630   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
421          0.503711        0.339738             0.313121       0.518182   
47           0.318140        0.287254             0.364811       0.539394   
292          0.184191        0.144213             0.167495       0.338384   
186          0.200294        0.191401             0.288966       0.283333   
414          0.081805        0.109794             0.136133       0.400000   
..                ...             ...                  ...            ...   
318          0.545427        0.462746             0.243936       0.641414   
375          0.381633        0.155834             0.268241       0.469697   
18           0.255567        0.346532             0.472068       0.263636   
168          0.432243        0.505858             0.518390       0.241414   
361          0.136035        0.078351             0.120477       0.381313   

     mean fractal dimension  ...  worst radius  worst texture  \
421                0.507582  ...      0.303451       0.168443   
47                 0.375105  ...      0.275347       0.424574   
292                0.310447  ...      0.206688       0.210821   
186                0.090354  ...      0.475987       0.382196   
414                0.062763  ...      0.331910       0.663380   
..                      ...  ...           ...            ...   
318                0.789174  ...      0.075774       0.303305   
375                0.331929  ...      0.321594       0.189765   
18                 0.084035  ...      0.689790       0.502665   
168                0.288332  ...      0.541089       0.541311   
361                0.147430  ...      0.223052       0.457889   

     worst perimeter  worst area  worst smoothness  worst compactness  \
421         0.317197    0.153362          0.396421           0.326193   
47          0.260919    0.141123          0.709437           0.377711   
292         0.191245    0.098358          0.509344           0.174162   
186         0.442203    0.301022          0.344912           0.210738   
414         0.297276    0.183396          0.288120           0.069244   
..               ...         ...               ...                ...   
318         0.090692    0.027502          0.336327           0.337156   
375         0.312217    0.166216          0.345572           0.220925   
18          0.679267    0.543846          0.528495           0.279138   
168         0.522387    0.362466          0.438685           0.345112   
361         0.211813    0.107157          0.282837           0.135256   

     worst concavity  worst concave points  worst symmetry  \
421         0.257109              0.380756        0.248768   
47          0.399840              0.717526        0.460280   
292         0.178994              0.362887        0.357776   
186         0.282588              0.539863        0.323477   
414         0.123562              0.225945        0.328800   
..               ...                   ...             ...   
318         0.368131              0.393471        0

In [45]:
#Train the support vector classifier
from sklearn.svm import SVC
clf = SVC(kernel='poly')
clf.fit(X_train, y_train)

SVC(kernel='poly')

In [46]:
#Predictions and evaluations
y_pred = clf.predict(X_test)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[ 60   5]
 [  3 120]]
              precision    recall  f1-score   support

           0       0.95      0.92      0.94        65
           1       0.96      0.98      0.97       123

    accuracy                           0.96       188
   macro avg       0.96      0.95      0.95       188
weighted avg       0.96      0.96      0.96       188

Accuracy: 0.9574468085106383


In [49]:
clf = SVC(kernel='sigmoid')
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[ 2 63]
 [64 59]]
              precision    recall  f1-score   support

           0       0.03      0.03      0.03        65
           1       0.48      0.48      0.48       123

    accuracy                           0.32       188
   macro avg       0.26      0.26      0.26       188
weighted avg       0.33      0.32      0.33       188

Accuracy: 0.324468085106383


In [50]:
clf = SVC(kernel='rbf')
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[ 61   4]
 [  2 121]]
              precision    recall  f1-score   support

           0       0.97      0.94      0.95        65
           1       0.97      0.98      0.98       123

    accuracy                           0.97       188
   macro avg       0.97      0.96      0.96       188
weighted avg       0.97      0.97      0.97       188

Accuracy: 0.9680851063829787


***Everything is being classified into a single class! Use Grid Search to search for the best parameters! (Scikitlearn GridSearchCV)***


In [77]:
#Set parameters
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV

In [79]:
model = SVC() 
model.fit(X_train, y_train)

predictions = model.predict(X_test) 
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.97      0.94      0.95        65
           1       0.97      0.98      0.98       123

    accuracy                           0.97       188
   macro avg       0.97      0.96      0.96       188
weighted avg       0.97      0.97      0.97       188



In [95]:
param_grid = {'C': [1, 10, 100],
              'kernel': ['linear', 'rbf', 'sigmoid']}

In [96]:
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3,n_jobs=-1)

In [97]:
#Fit grid (Note to self: first it runs the same loop with cross-validation to find the best parameter combination. Once it has the best combination, it runs fit again on all data passed to fit (without cross-validation), to built a single new model using the best parameter setting.)
grid.fit(X_train, y_train) 

Fitting 5 folds for each of 9 candidates, totalling 45 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done  45 out of  45 | elapsed:    0.0s finished


GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [1, 10, 100],
                         'kernel': ['linear', 'rbf', 'sigmoid']},
             verbose=3)

In [105]:
#Call the best parameters
print(grid.best_params_) 
grid_predictions = grid.predict(X_test)
print(classification_report(y_test, grid_predictions))
from sklearn.metrics import confusion_matrix


{'C': 100, 'kernel': 'linear'}
              precision    recall  f1-score   support

           0       0.94      0.95      0.95        65
           1       0.98      0.97      0.97       123

    accuracy                           0.96       188
   macro avg       0.96      0.96      0.96       188
weighted avg       0.96      0.96      0.96       188



In [ ]:
#print best score

In [104]:
# print the confusion matrix
confusion_matrix(y_test, y_pred)

array([[ 61,   4],
       [  2, 121]], dtype=int64)

# Discussion of results