# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [15]:
print (numpy.version.version)
numpy.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kovac/anaconda3/envs/machinelearning\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/kovac/anaconda3/envs/machinelearning\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/kovac/anaconda3/envs/machinelearning\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\

#### 3. Create a null vector of size 10 (★☆☆)

In [23]:
null_array = np.zeros(10)
print(null_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [28]:
# one method, get the size of one elements and multiply by the size of the array
print(null_array.size) # size of the array
print(null_array.itemsize) # memory size of one element in the array in bytes
print(x.size * x.itemsize) # memory size of the whole array in bytes, multiplying one element's memory size by the amount of elements in the array

# using nbytes attribute provides the same result
print(null_array.nbytes)

10
8
80
80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [29]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [36]:
n_array = np.zeros(10)
n_array[4] = 1
print(n_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [35]:
v_array = np.arange(10,49)   #array within range (start, stop, step)
print(v_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [38]:
print(np.flip(v_array, 0))

[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [44]:
matrix_array = np.arange(0,9)
matrix_array = matrix_array.reshape(3,3)
print(matrix_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [3]:
i_array = np.array([1,2,0,0,4,0])
np.where(i_array != 0)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [51]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [55]:
np.random.randint(100, size=(3,3,3))
#limit the random to an integers under 100 and not decimals, for easier testing

array([[[21, 87, 28],
        [78,  1, 72],
        [54,  6, 64]],

       [[20,  8, 87],
        [18, 99, 99],
        [79, 64, 71]],

       [[81, 32, 14],
        [19,  5, 43],
        [12, 66, 41]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [98]:
v = np.random.random((10,10))

# two ways to call the min and max

print(numpy.amax(v))
print(numpy.amin(v))
np.min(v), np.max(v)

0.995760068034232
0.006147138070599412


(0.006147138070599412, 0.995760068034232)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [99]:
vec = np.random.random(30)
numpy.mean(vec)

0.4081681204374197

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [121]:
d_array = np.ones(9)
d_array[4] = 0
print(d_array.reshape(3, 3))

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [258]:
d_array = np.ones((3,3))
d_array[1:-1,1:-1] = 0
print(d_array)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [126]:
d_array = np.full((3,3), 1)
d_array[1:-1,1:-1]=0
d_array

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [180]:
b_array = np.full((5,5), 3)
numpy.pad(b_array, (1, 1), 'constant', constant_values = 0)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 3, 3, 3, 3, 3, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [183]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [187]:
data = np.array([1, 2, 3, 4])
numpy.diag((data), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [216]:
d_array = np.array([[0,1], [1,0]])
d = np.tile(d_array, (4,4))
print(d)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [227]:
d = np.zeros ((8,8), dtype=int)
d[1::2, ::2]= 1
d[::2, 1::2] = 1      #important to run this line, otherwise the fourth line gets all 1
print (d)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [17]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [5]:
d_array = np.array([[0,1], [1,0]])
d = np.tile(d_array, (4,4))
print(d)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [20]:

#standardisation, z-score normalization

rm = np.random.random((5,5))
mean = np.mean(rm)
stadev = np.std(rm)
normal = ((rm-mean) / stadev)
#print(rm)               
#print(mean)
#print(stadev)
print(normal)

print( )

#min-max normali


rmax, rmin = rm.max(), rm.min()
r = (rm-rmin)/(rmax-rmin)
print (r)

[[ 0.1822843  -1.49810096  0.12582003 -0.9665423   1.15856999]
 [ 1.57430059  0.39673188  0.90912335  1.3438933  -0.77906593]
 [-1.13171304 -0.24377627 -0.40958978  1.17833468  0.25328589]
 [ 1.57617905  0.79019327  0.88748757 -0.61704345  0.63025476]
 [-1.05924324 -1.09994329 -0.21617305 -1.6992518  -1.28601557]]

[[0.57443927 0.06141202 0.55720054 0.22369866 0.87250255]
 [0.9994265  0.63991083 0.79634566 0.92908238 0.28093582]
 [0.17327148 0.44436155 0.39373813 0.87853678 0.59611629]
 [1.         0.76003591 0.78974019 0.33040183 0.71120615]
 [0.19539675 0.18297089 0.4527889  0.         0.1261624 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [36]:
Color = np.dtype([("r", np.ubyte), 
                ("g", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
matrix1 = np.random.random((5,3))
#print(matrix1)

print()

matrix2 = np.random.random((3,2))
#print(matrix2)



product = np.matmul(matrix1, matrix2)
print(product)

print()

product2 = np.dot(matrix1, matrix2)
print(product2)


[[0.46734103 0.29731063]
 [0.73469215 0.43853905]
 [0.28499995 0.07248964]
 [0.34611558 0.12973977]
 [0.66130142 0.43141093]]

[[0.46734103 0.29731063]
 [0.73469215 0.43853905]
 [0.28499995 0.07248964]
 [0.34611558 0.12973977]
 [0.66130142 0.43141093]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
import numpy as np
oneD = np.arange(10)

oneD[3:8] = np.negative(oneD[3:8])

arr2 = []

for x in oneD:
    if x > 3 and x <=8:
        x = x*-1
        arr2.append(x)
    else:
        arr2.append(x)

print(oneD)
print(arr2)

#print(oneD[3:8])




oneD[(3 < oneD) & (oneD <= 8)] *= -1

print(oneD)

[ 0  1  2 -3 -4 -5 -6 -7  8  9]
[0, 1, 2, -3, -4, -5, -6, -7, -8, 9]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [36]:
Z = np.arange(11)

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)    not legal

[         1          1          4         27        256       3125
      46656     823543   16777216  387420489 1410065408]
[  0   1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [37]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-37-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-37-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [32]:
farr = np.random.uniform(-5, +5, 5)       
print(farr)
#np.round(farr, 0)                  #rounds, but not from zero but to nearest integer


a = 5.2          # base idea, get a float number
b = a % 1        # modulus, get remainder of the float
c = 1 - b        # get the other half  of the remainder, necessary to get to the next integer
d = a + c        # add the other remaining half, to get to the next integer

z = 0

zs = 0

farr1 = []

for x in farr:
    z = x % 1

    if x > 0:
        zs = 1 - z
        zss = x + zs
    else:
        zs = 0 + z
        zss = x - zs
    farr1.append(zss)

print(farr1)


# for whatever reason, this is the regular, correct solution:

print (np.copysign(np.ceil(np.abs(farr)), farr))

[3.49431459 3.26705988 3.01159615 3.55299029 4.49023422]
[4.0, 4.0, 4.0, 4.0, 5.0]
[4. 4. 4. 4. 5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [39]:
a1 = np.arange(1,5)
a2 = np.arange(2,8)

print(a1)
print(a2)

a3 = np.intersect1d(a1,a2)

print(a3)

[1 2 3 4]
[2 3 4 5 6 7]
[2 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [46]:
old_settings = np.seterr(all='ignore')
np.seterr(over='raise')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [47]:
np.seterr(**old_settings)

{'divide': 'ignore', 'over': 'raise', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [48]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [58]:
today = np.datetime64('today')
print(today)

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2021-01-03
2021-01-02
2021-01-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [63]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1

B = np.ones(3)*2

C = np.ones(3)*3

np.add(A,B, out=A)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)