## Linear Algebra Quiz #2

![title](./img/2_1.jpeg)

We strongly suggest working with numpy :)

In [9]:
#Do your imports here
import numpy as np

![title](./img/2_2.png)
- Which vectors below define a plane spanned by a linear combination?

In [63]:
    a = np.array([1, 2, 3])
    b = np.array([2, 2, 2])
    c = np.array([8, 8, 8])
    


def plane(a,b,c):
    #returns false if the vectors do define a plane and returns which are those vectors if true
    
        """ 
        The intuition is that x [1,0,0], y [0, 1, 0]  --> will form a plane
        That happens because they linearly independent --> There is an angle between both vectors that is not 0 or 180*.
        x [1,0,0] and -x [-1,0,0], do not form a plane, only a line
        """
    # dot product between the two vector
    #we want to look at the angle between the two vectors (resulting vector)
    
        unit_a = a / np.linalg.norm(b)
        print(unit_a)
        
        unit_a1 = a / np.linalg.norm(c)
        print(unit_a1)
        
        unit_b = b / np.linalg.norm(a)
        print(unit_b)
        
        unit_b1 = b / np.linalg.norm(c)
        print(unit_b1)
        
        unit_c = c / np.linalg.norm(a)
        print(unit_c)
        
        unit_c1 = c / np.linalg.norm(b)
        print(unit_c1)
        
        
        dot_product_ab = np.dot(unit_a, unit_b)
      
        angle_ab = np.arccos(dot_product_ab)
        
        
        #dot_product_bc = np.dot(unit_b, unit_c)   # doesnt fucking work!!!!!!!
        
        #print(dot_product_bc)
        
        print(angle_ab)
        
        return()
    
plane(a,b,c)    
    # check a,b
    # check b,c
    # check a,c

[0.28867513 0.57735027 0.8660254 ]
[0.07216878 0.14433757 0.21650635]
[0.53452248 0.53452248 0.53452248]
[0.14433757 0.14433757 0.14433757]
[2.13808994 2.13808994 2.13808994]
[2.30940108 2.30940108 2.30940108]
0.38759668665518016


()

In [61]:
def plane(a,b,c):
    #returns false if the vectors do define a plane and returns which are those vectors if true
    
    matrix = np.stack((a,b,c))
    
    lambdas, V = np.linalg.eig(matrix.T)
    
    e = 0.000000001
    
    plane_test = abs(lambdas) > e 
    
    if plane_test.sum() >= 2:
        
        print('Vectors form a plane!')
        
        vectors = matrix[plane_test]
        return vectors
    else:
        print('Vectors are all linearly dependent. No plane exists.')

In [40]:
a = np.array([1,2,3])
b = np.array([2,2,2])
c = np.array([4,7,9])

plane(a,b,c)

Vectors form a plane!


array([[1, 2, 3],
       [2, 2, 2],
       [4, 7, 9]])

In [4]:
# Harder exercise

def complete_plane(#inputs):
    
#returns the first set of vectors to complete a plane, false otherwise

SyntaxError: unexpected EOF while parsing (<ipython-input-4-5f93bfa34679>, line 5)

![title](./img/2_3.png)
- What is the solution for a and b?

In [ ]:
# do you need a function for this? What is the most efficient way to solve it?
#2*a + 3*b +1 =0

#10*a+15*b+5 = 0

![title](./img/2_4.png)
- What is the solution for a and b?

In [ ]:
# Idem. Do you need a function for this? What is the most efficient way to solve it?